### DIRECT
POST localhost:8080/v1/persons
exchange: ex.direct
rk: a.b.c
Content-Type: application/json

{
  "name": "João",
  "birthdate": "1993-04-01",
  "gender": "MALE"
}

### FANOUT
POST localhost:8080/v1/persons
exchange: ex.fanout
Content-Type: application/json

{
  "name": "João",
  "birthdate": "1993-04-01",
  "gender": "MALE"
}

### HEADERS
POST localhost:8080/v1/persons
exchange: ex.headers
hhh: 111
Content-Type: application/json

{
  "name": "João",
  "birthdate": "1993-04-01",
  "gender": "MALE"
}

### TOPIC
POST localhost:8080/v1/persons
exchange: ex.topic
rk: a.1.b
Content-Type: application/json

{
  "name": "João",
  "birthdate": "1993-04-01",
  "gender": "MALE"
}

### EXCHANGES
POST localhost:8080/v1/persons
exchange: exchange-a
rk: redirect
Content-Type: application/json

{
  "name": "João",
  "birthdate": "1993-04-01",
  "gender": "MALE"
}

###
